import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import About from "./About";
import Image from "next/image";
import Link from "next/link";

// const Index: NextPage = (props) => {
//   const { dataFact } = props;
//   return (
//     <>
//       <Head>
//         <title>api-test</title>
//         <meta name="description" content="Generated by Create Next Stack." />
//       </Head>
//       <div>
//         {dataFact.map((data) => {
//           return (
//             <div key={data._id}>
//               <p>{data.fact}</p>
//             </div>
//           );
//         })}
//       </div>
//     </>
//   );
// };

// export default Index;

interface FactProps {
  dataFact: [];
}

export default function Index(props: FactProps) {
  const { dataFact } = props;
  return (
    <>
      <Head>
        <title>api-test</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div>
        {/* {dataFact.map((data) => (
            <div key={data}>
              <p>{data.results.url}</p>
            </div>

        ))} */}
        <Image src={dataFact.results[0].url} alt="ayam" />
        {/* <Image src={dataFact.results[0].url} alt="" width={500} height={500} /> */}
        
      </div>
      {console.log(dataFact.results.url)}
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch('https://nekos.best/api/v2/husbando');
  const dataFact = await res.json();

  return {
      props: {
          dataFact,
      },
  }
}

// interface ResultsProps {
//   results: [];
// }

// export default function Index(props: ResultsProps) {
//   const { results } = props;
//   return (
//     <>
//       <Head>
//         <title>api-test</title>
//         <meta name="description" content="Generated by Create Next Stack." />
//       </Head>
//       <div>
//         {results.map((result) => {
//           return (
//             <div key={result.id}>
//               <img src={result.url} alt="" />
//             </div>
//           );
//         })}
//       </div>
//     </>
//   );
// }

// export async function getServerSideProps() {
//   const res = await fetch("https://nekos.best/api/v2/neko");
//   const results = await res.json();
//   return {
//     props: {
//       results,
//     },
//   };
// }
